# Generated by Django 5.2.5 on 2025-08-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_recipe_options_alter_useremail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
